#!/usr/bin/env python3
"""
---
title: "Invalid File Notifier"
name: github-skill-organizer
description: "Background daemon that monitors logs/invalid_files/ and auto-creates GitHub Issues for unparseable frontmatter files. Pure background execution, no agent intervention required. v1.0.0 initial release."
version: "1.0.0"
github_repository: nervlin4444/ai.skills.incubation
target_branch: main
updated_at: "2026-05-23T22:45:00+08:00"
fixes: []
auth_config:
  provider: github
  auth_method: token
  token_env_var: GITHUB_TOKEN
  env_file_path: ../.env
file_mapping:
  local_path: scripts/invalid_file_notifier.py
  github_path: github-skill-organizer/scripts/invalid_file_notifier.py
---
"""

import os
import sys
import json
import time
import urllib.request
import urllib.error
from pathlib import Path
from datetime import datetime, timezone

class InvalidFileNotifier:
    """
    Background daemon for auto-creating GitHub Issues when invalid files are detected.
    Monitors logs/invalid_files/ directory and creates issues with standard format.
    """

    CHECK_INTERVAL = 60
    ISSUE_LABELS = ["bug", "frontmatter", "auto-detected"]
    MAX_RETRY = 3

    def __init__(self, base_dir: str = None, owner: str = None, repo: str = None, token: str = None):
        if base_dir is None:
            self.base_dir = Path.home() / ".workbuddy" / "skills" / "github-skill-organizer" / "logs" / "invalid_files"
        else:
            self.base_dir = Path(base_dir).expanduser().resolve()
        self.base_dir.mkdir(parents=True, exist_ok=True)
        self.owner = owner or os.environ.get("GITHUB_OWNER", "nervlin4444")
        self.repo = repo or os.environ.get("GITHUB_REPO", "ai.skills.incubation")
        self.token = token or os.environ.get("GITHUB_TOKEN", "")
        self.api_base = "https://api.github.com"

    def _github_api_call(self, method: str, endpoint: str, payload: dict = None) -> dict:
        """Direct GitHub API call for system-level daemon (not a skill script)."""
        url = f"{self.api_base}/{endpoint}"
        data = json.dumps(payload).encode("utf-8") if payload else None
        req = urllib.request.Request(url, data=data, method=method)
        req.add_header("Authorization", f"Bearer {self.token}")
        req.add_header("Accept", "application/vnd.github+json")
        req.add_header("X-GitHub-Api-Version", "2022-11-28")
        if data:
            req.add_header("Content-Type", "application/json")
        try:
            with urllib.request.urlopen(req, timeout=30) as resp:
                return json.loads(resp.read().decode("utf-8"))
        except urllib.error.HTTPError as e:
            return {"error": True, "status": e.code, "message": str(e)}
        except Exception as e:
            return {"error": True, "status": 0, "message": str(e)}

    def get_pending_invalid_files(self) -> list:
        """Get all invalid file records with notification_status == pending."""
        pending = []
        for log_file in sorted(self.base_dir.glob("invalid_*.json")):
            try:
                with open(log_file, "r", encoding="utf-8") as f:
                    record = json.load(f)
                if record.get("notification_status") == "pending":
                    record["_log_file"] = str(log_file)
                    pending.append(record)
            except Exception:
                continue
        return pending

    def create_github_issue(self, record: dict) -> dict:
        """Create GitHub Issue for invalid file with standard format."""
        original_name = record.get("original_name", "unknown")
        reason = record.get("reason", "unknown")
        file_path = record.get("path", "unknown")

        skill_name = self._guess_skill_name(original_name)

        title = f"[INVALID] [{skill_name}] {original_name} - {reason}"

        body_lines = [
            "## Auto-Detected Invalid File",
            "",
            f"**File:** `{original_name}`",
            f"**Path:** `{file_path}`",
            f"**Reason:** `{reason}`",
            f"**Detected:** {record.get('timestamp', 'unknown')}",
            "",
            "## Root Cause",
            "This file has frontmatter/docstring traces but the structure is unparseable by local_scanner.",
            "Common causes:",
            "- Docstring does not end immediately after frontmatter `---`",
            "- Chinese or full-width punctuation inside .py docstring",
            "- Missing `name` field in frontmatter",
            "- File was not generated by skill_files_designer",
            "",
            "## Fix Required",
            "1. Regenerate this file using `skill_files_designer.py`",
            "2. Ensure docstring structure: `\"\"\"` -> `---` -> frontmatter -> `---` -> `\"\"\"`",
            "3. Verify no Chinese/full-width punctuation in .py files (LOCK-016)",
            "4. Re-upload with commit message containing `Fixes #{issue_number}`",
            "",
            "## Auto-Close Condition",
            "This issue will be auto-closed when the file is successfully re-uploaded with a valid frontmatter.",
        ]
        body = "\n".join(body_lines)

        payload = {
            "title": title,
            "body": body,
            "labels": self.ISSUE_LABELS,
        }

        result = self._github_api_call("POST", f"repos/{self.owner}/{self.repo}/issues", payload)
        return result

    def _guess_skill_name(self, filename: str) -> str:
        """Guess skill name from filename."""
        parts = filename.replace("_", ".").split(".")
        if len(parts) >= 2:
            return parts[0]
        return "unknown"

    def update_notification_status(self, record: dict, status: str, issue_number: int = None):
        """Update the log file with notification status."""
        log_file = record.get("_log_file")
        if not log_file:
            return
        try:
            with open(log_file, "r", encoding="utf-8") as f:
                data = json.load(f)
            data["notification_status"] = status
            if issue_number:
                data["github_issue_number"] = issue_number
                data["github_issue_url"] = f"https://github.com/{self.owner}/{self.repo}/issues/{issue_number}"
            with open(log_file, "w", encoding="utf-8") as f:
                json.dump(data, f, indent=2, ensure_ascii=False)
        except Exception as e:
            print(f"[NOTIFIER] Failed to update status: {e}")

    def run_once(self) -> dict:
        """Run one check cycle. Returns summary."""
        pending = self.get_pending_invalid_files()
        if not pending:
            return {"checked": 0, "notified": 0, "errors": 0}

        print(f"[NOTIFIER] Found {len(pending)} pending invalid file(s)")
        notified = 0
        errors = 0

        for record in pending:
            print(f"[NOTIFIER] Processing: {record.get('original_name', 'unknown')}")
            result = self.create_github_issue(record)
            if result.get("error"):
                print(f"[NOTIFIER] ERROR creating issue: {result.get('message', 'unknown')}")
                errors += 1
                continue
            issue_number = result.get("number")
            if issue_number:
                self.update_notification_status(record, "notified", issue_number)
                print(f"[NOTIFIER] Created GitHub Issue #{issue_number}: {result.get('html_url', '')}")
                notified += 1
            else:
                print(f"[NOTIFIER] WARNING: No issue number in response")
                errors += 1

        return {"checked": len(pending), "notified": notified, "errors": errors}

    def run_daemon(self):
        """Run as background daemon with infinite loop."""
        print(f"[NOTIFIER] Daemon started, checking every {self.CHECK_INTERVAL}s")
        print(f"[NOTIFIER] Monitoring: {self.base_dir}")
        print(f"[NOTIFIER] Target repo: {self.owner}/{self.repo}")
        while True:
            try:
                summary = self.run_once()
                if summary["checked"] > 0:
                    print(f"[NOTIFIER] Cycle complete: {summary}")
            except Exception as e:
                print(f"[NOTIFIER] Cycle error: {e}")
            time.sleep(self.CHECK_INTERVAL)

def main():
    import argparse
    parser = argparse.ArgumentParser(description="Invalid File Notifier Daemon v1.0.0")
    parser.add_argument("--daemon", action="store_true", help="Run as background daemon")
    parser.add_argument("--once", action="store_true", help="Run one check cycle and exit")
    parser.add_argument("--owner", help="GitHub owner")
    parser.add_argument("--repo", help="GitHub repo")
    parser.add_argument("--token", help="GitHub token (or use GITHUB_TOKEN env)")
    args = parser.parse_args()

    notifier = InvalidFileNotifier(owner=args.owner, repo=args.repo, token=args.token)

    if args.once:
        summary = notifier.run_once()
        print(json.dumps(summary, indent=2))
        sys.exit(0 if summary["errors"] == 0 else 1)
    elif args.daemon:
        notifier.run_daemon()
    else:
        parser.print_help()

if __name__ == "__main__":
    main()
